//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeffWilcox.FourthAndMayor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeffWilcox.FourthAndMayor.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add photo.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check-in....
        /// </summary>
        public static string AdvancedCheckIn {
            get {
                return ResourceManager.GetString("AdvancedCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the tile could not be created at this time..
        /// </summary>
        public static string AppTileManager_Error_TileCreationGeneric {
            get {
                return ResourceManager.GetString("AppTileManager_Error_TileCreationGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network connection was not available to download the image needed to create the tile. Please try again later..
        /// </summary>
        public static string AppTileManager_NoNetwork {
            get {
                return ResourceManager.GetString("AppTileManager_NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to read the categories list..
        /// </summary>
        public static string Data_Error_CannotReadCategories {
            get {
                return ResourceManager.GetString("Data_Error_CannotReadCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading place info.
        /// </summary>
        public static string DownloadingPlaceInfo {
            get {
                return ResourceManager.GetString("DownloadingPlaceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string Group_Badge_Name {
            get {
                return ResourceManager.GetString("Group_Badge_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here now.
        /// </summary>
        public static string HereNow {
            get {
                return ResourceManager.GetString("HereNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to establish a mayorship, consider frequenting this place..
        /// </summary>
        public static string HowToEstablishMayorship {
            get {
                return ResourceManager.GetString("HowToEstablishMayorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early morning..
        /// </summary>
        public static string InformalEarlyMorning {
            get {
                return ResourceManager.GetString("InformalEarlyMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon..
        /// </summary>
        public static string InformalGoodAfternoon {
            get {
                return ResourceManager.GetString("InformalGoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening..
        /// </summary>
        public static string InformalGoodEvening {
            get {
                return ResourceManager.GetString("InformalGoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning..
        /// </summary>
        public static string InformalGoodMorning {
            get {
                return ResourceManager.GetString("InformalGoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having a good night?.
        /// </summary>
        public static string InformalGoodNight {
            get {
                return ResourceManager.GetString("InformalGoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings..
        /// </summary>
        public static string InformalGreetings {
            get {
                return ResourceManager.GetString("InformalGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello..
        /// </summary>
        public static string InformalHello {
            get {
                return ResourceManager.GetString("InformalHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey..
        /// </summary>
        public static string InformalHey {
            get {
                return ResourceManager.GetString("InformalHey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi..
        /// </summary>
        public static string InformalHi {
            get {
                return ResourceManager.GetString("InformalHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string InformalLoading {
            get {
                return ResourceManager.GetString("InformalLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunchtime!.
        /// </summary>
        public static string InformalLunchtime {
            get {
                return ResourceManager.GetString("InformalLunchtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been to {0} of {1} places.
        /// </summary>
        public static string ListYouveBeenTo {
            get {
                return ResourceManager.GetString("ListYouveBeenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been to this place.
        /// </summary>
        public static string ListYouveBeenToSingular {
            get {
                return ResourceManager.GetString("ListYouveBeenToSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploring....
        /// </summary>
        public static string LoadingExploring {
            get {
                return ResourceManager.GetString("LoadingExploring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading to-do&apos;s.
        /// </summary>
        public static string LoadingToDos {
            get {
                return ResourceManager.GetString("LoadingToDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Opt-In.
        /// </summary>
        public static string LocationOptIn {
            get {
                return ResourceManager.GetString("LocationOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to road view.
        /// </summary>
        public static string MapRoadView {
            get {
                return ResourceManager.GetString("MapRoadView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to satellite view.
        /// </summary>
        public static string MapSatelliteView {
            get {
                return ResourceManager.GetString("MapSatelliteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no mayor.
        /// </summary>
        public static string NoMayor {
            get {
                return ResourceManager.GetString("NoMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an optional shout out.
        /// </summary>
        public static string OptionalShoutOut {
            get {
                return ResourceManager.GetString("OptionalShoutOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quick check-in.
        /// </summary>
        public static string QuickCheckIn {
            get {
                return ResourceManager.GetString("QuickCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Notifications.
        /// </summary>
        public static string SeeAllNotifications {
            get {
                return ResourceManager.GetString("SeeAllNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string ShareMail {
            get {
                return ResourceManager.GetString("ShareMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        public static string ShareMessaging {
            get {
                return ResourceManager.GetString("ShareMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Network.
        /// </summary>
        public static string ShareSocialNetwork {
            get {
                return ResourceManager.GetString("ShareSocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE.
        /// </summary>
        public static string ShareTaskTitle {
            get {
                return ResourceManager.GetString("ShareTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to special here.
        /// </summary>
        public static string SpecialHere {
            get {
                return ResourceManager.GetString("SpecialHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to special nearby.
        /// </summary>
        public static string SpecialNearby {
            get {
                return ResourceManager.GetString("SpecialNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to special unlocked.
        /// </summary>
        public static string SpecialUnlocked {
            get {
                return ResourceManager.GetString("SpecialUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing tile graphics.
        /// </summary>
        public static string Status_PreparingTileGraphics {
            get {
                return ResourceManager.GetString("Status_PreparingTileGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4ᵀᴴ &amp; MAYOR.
        /// </summary>
        public static string Stylized4thAndMayor {
            get {
                return ResourceManager.GetString("Stylized4thAndMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to touch to learn more.
        /// </summary>
        public static string TouchToLearnMore {
            get {
                return ResourceManager.GetString("TouchToLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to touch to see nearby specials.
        /// </summary>
        public static string TouchToSeeNearbySpecials {
            get {
                return ResourceManager.GetString("TouchToSeeNearbySpecials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Recent Notifications.
        /// </summary>
        public static string YourRecentNotifications {
            get {
                return ResourceManager.GetString("YourRecentNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your to-dos.
        /// </summary>
        public static string YourTodos {
            get {
                return ResourceManager.GetString("YourTodos", resourceCulture);
            }
        }
    }
}
